obj={}
require("socket.io").listen(
require("http").createServer((req,res)=>{
res.writeHead(200,{"content-type":"text/html"})
res.write('<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script>')
res.write('<script>socket=io()</script>')
res.write('<script>socket.on("msg",(e)=>{eval(e.script)})</script>')
res.end()
}).listen(process.env.PORT||3000,()=>{console.log("Здравствуйте!")})
).on("connection",(socket)=>{
socket.i=Math.random()
obj[socket.i]={x:0,y:0,xs:0,ys:0}
socket.emit("msg",{script:'k=[]'})
socket.emit("msg",{script:'document.body.style.margin="0"'})
socket.emit("msg",{script:'c=document.createElement("canvas")'})
socket.emit("msg",{script:'document.body.appendChild(c)'})
socket.emit("msg",{script:'ctx=c.getContext("2d")'})
socket.emit("msg",{script:'onkeydown=onkeyup=(e)=>{k[e.keyCode]=e.type=="keydown"}'})
socket.emit("msg",{script:'setInterval(()=>{for(i=0;i<400;i++){if(k[i]){socket.emit("key",{code:i})}}},1)'})
socket.on("key",(e)=>{
if(e.code==37){obj[socket.i].xs-=0.001}
if(e.code==38){obj[socket.i].ys-=0.001}
if(e.code==39){obj[socket.i].xs+=0.001}
if(e.code==40){obj[socket.i].ys+=0.001}
})
setInterval(()=>{
socket.emit("msg",{script:'c.width=innerWidth'})
socket.emit("msg",{script:'c.height=innerHeight'})
for(i in obj){
socket.emit("msg",{script:'ctx.fillStyle="rgba(250,200,150,1)"'})
socket.emit("msg",{script:'ctx.fillRect('+eval(obj[i].x-obj[socket.i].x)+'+innerWidth/2-16,'+eval(obj[i].y-obj[socket.i].y)+'+innerHeight/2-16,32,32)'})
socket.emit("msg",{script:'ctx.lineWidth="4"'})
socket.emit("msg",{script:'ctx.strokeStyle="rgba(200,175,150,1)"'})
socket.emit("msg",{script:'ctx.strokeRect('+eval(obj[i].x-obj[socket.i].x)+'+innerWidth/2-16,'+eval(obj[i].y-obj[socket.i].y)+'+innerHeight/2-16,32,32)'})
}},20)
})
setInterval(()=>{
for(i in obj){
obj[i].x+=obj[i].xs
obj[i].y+=obj[i].ys
obj[i].xs*=0.999
obj[i].ys*=0.999
}},1)
